from django.urls import path
from .views import (
    AddFriendView, FriendListView, DeleteFriendView,
    SetFriendRemarkView, FriendGroupListView, CreateFriendGroupView, SetFriendGroupView,
    ConversationListView, CreatePrivateConversationView,
    CreateGroupConversationView, MessageListView, MessageCreateView,
    MarkMessagesReadView, FileUploadView,
    FriendRequestListView, SendFriendRequestView,
    AcceptFriendRequestView, RejectFriendRequestView,
    MessageSearchView, PinConversationView, MuteConversationView, HideConversationView,
    FavoriteMessageView, FavoriteMessageListView, ForwardMessageView,
    GroupAnnouncementView, GroupAvatarView, SetGroupAdminView, JoinGroupByInviteCodeView,
    KickGroupMemberView, LeaveGroupView, DissolveGroupView,
    UpdateGroupNameView, TransferGroupOwnerView,
    EditMessageView, MuteGroupMemberView, SetGroupNicknameView,
    GroupTransferRecordView, SetFriendTagsView, UserProfileView,
    BlacklistView, BlockUserView, UnblockUserView,
)

urlpatterns = [
    path('friends/add/', AddFriendView.as_view(), name='add_friend'),
    path('friends/', FriendListView.as_view(), name='friend_list'),
    path('friends/delete/', DeleteFriendView.as_view(), name='delete_friend'),
    path('friends/remark/', SetFriendRemarkView.as_view(), name='set_friend_remark'),
    path('friends/groups/', FriendGroupListView.as_view(), name='friend_group_list'),
    path('friends/groups/create/', CreateFriendGroupView.as_view(), name='create_friend_group'),
    path('friends/groups/set/', SetFriendGroupView.as_view(), name='set_friend_group'),
    path('conversations/', ConversationListView.as_view(), name='conversation_list'),
    path('conversations/private/', CreatePrivateConversationView.as_view(), name='create_private_conversation'),
    path('conversations/group/', CreateGroupConversationView.as_view(), name='create_group_conversation'),
    path('conversations/<int:conversation_id>/messages/', MessageListView.as_view(), name='message_list'),
    path('conversations/<int:conversation_id>/mark-read/', MarkMessagesReadView.as_view(), name='mark_messages_read'),
    path('conversations/<int:conversation_id>/pin/', PinConversationView.as_view(), name='pin_conversation'),
    path('conversations/<int:conversation_id>/mute/', MuteConversationView.as_view(), name='mute_conversation'),
    path('conversations/<int:conversation_id>/hide/', HideConversationView.as_view(), name='hide_conversation'),
    path('conversations/<int:conversation_id>/announcement/', GroupAnnouncementView.as_view(), name='group_announcement'),
    path('conversations/<int:conversation_id>/avatar/', GroupAvatarView.as_view(), name='group_avatar'),
    path('conversations/<int:conversation_id>/admin/', SetGroupAdminView.as_view(), name='set_group_admin'),
    path('conversations/<int:conversation_id>/kick/', KickGroupMemberView.as_view(), name='kick_member'),
    path('conversations/<int:conversation_id>/leave/', LeaveGroupView.as_view(), name='leave_group'),
    path('conversations/<int:conversation_id>/dissolve/', DissolveGroupView.as_view(), name='dissolve_group'),
    path('conversations/<int:conversation_id>/name/', UpdateGroupNameView.as_view(), name='update_group_name'),
    path('conversations/<int:conversation_id>/transfer/', TransferGroupOwnerView.as_view(), name='transfer_group_owner'),
    path('conversations/<int:conversation_id>/transfer-records/', GroupTransferRecordView.as_view(), name='transfer_records'),
    path('conversations/<int:conversation_id>/mute-member/', MuteGroupMemberView.as_view(), name='mute_group_member'),
    path('conversations/<int:conversation_id>/nickname/', SetGroupNicknameView.as_view(), name='set_group_nickname'),
    path('conversations/join/', JoinGroupByInviteCodeView.as_view(), name='join_group_by_invite'),
    path('friends/<int:friend_id>/tags/', SetFriendTagsView.as_view(), name='set_friend_tags'),
    path('users/<int:user_id>/profile/', UserProfileView.as_view(), name='user_profile'),
    path('messages/', MessageCreateView.as_view(), name='message_create'),
    path('messages/<int:message_id>/edit/', EditMessageView.as_view(), name='edit_message'),
    path('messages/search/', MessageSearchView.as_view(), name='message_search'),
    path('messages/favorite/', FavoriteMessageView.as_view(), name='favorite_message'),
    path('messages/favorites/', FavoriteMessageListView.as_view(), name='favorite_messages'),
    path('messages/forward/', ForwardMessageView.as_view(), name='forward_message'),
    path('upload/', FileUploadView.as_view(), name='file_upload'),
    path('friend-requests/', FriendRequestListView.as_view(), name='friend_request_list'),
    path('friend-requests/send/', SendFriendRequestView.as_view(), name='send_friend_request'),
    path('friend-requests/<int:request_id>/accept/', AcceptFriendRequestView.as_view(), name='accept_friend_request'),
    path('friend-requests/<int:request_id>/reject/', RejectFriendRequestView.as_view(), name='reject_friend_request'),
    path('blacklist/', BlacklistView.as_view(), name='blacklist'),
    path('blacklist/block/', BlockUserView.as_view(), name='block_user'),
    path('blacklist/unblock/', UnblockUserView.as_view(), name='unblock_user'),
]
