# Generated by Django 6.0.4 on 2026-04-25 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversationmember_invited_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.CreateModel(
            name='GroupTransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_records', to='chat.conversation')),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ownership', to=settings.AUTH_USER_MODEL)),
                ('old_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferred_ownership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_transfer_records',
                'ordering': ['-transferred_at'],
            },
        ),
    ]
